dist: bionic
language: node_js
node_js:
  - 10.18.0
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - rm -rf dist/
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_95b928af7628_key -iv $encrypted_95b928af7628_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -azv ./dist/ $DEPLOY_USER@$SERVER:$DEPLOY_DIR/ --delete
  on:
    branch: master
